### ISSUE TITLE
Ground vehicles in weird positions after spawn

### ISSUE THREAD

**Issue by Toonu** [gavazquez/LunaMultiPlayer#46] opened 2017-11-29 08:35 UTC
Problem: We saw each other in godo positions, but not complete vessel or in rolled position.

Reproduction steps: I spawned rover and drive near the end of bubble of launchapd, when he drove out of bubble I saw only root part and he saw me in weird rolled position.

Log will be added by HellBox

![screenshot3](https://user-images.githubusercontent.com/4078304/33365397-623f1c3c-d4e8-11e7-8fa9-3277f5e84642.png)
![screenshot4](https://user-images.githubusercontent.com/4078304/33365398-6260ef06-d4e8-11e7-9b70-79f3df1866ab.png)
![screenshot_1](https://user-images.githubusercontent.com/4078304/33365430-78ee0042-d4e8-11e7-925d-64f47e26c964.png)

Pastebin crashed when I tried post there the 50MB log so...
Link: https://www.dropbox.com/s/g6m1g6i99nihafi/KSP.log?dl=0

**Comment by gavazquez** [comment] 2017-11-29 13:05
I think that the issue is because you both have different "terrain detail" settings

**Comment by gavazquez** [comment] 2017-11-30 11:20
Fixed the issue with the terrain but this still happens. It happens only with linux clients as it's similar to issue #48

I will set it to low priority and help wanted as I don't have neither linux nor the time to install it. Perhaps some linux dev can help on this...

**Comment by TheHellBox** [comment] 2017-11-30 15:08
Fixed by using LC_ALL=C https://wiki.kerbalspaceprogram.com/wiki/Linux (Running on non-English localized systems)

**Closed** 2017-11-30 23:54 UTC
Labels: bug, help wanted, linux, medium priority
